In [ ]:
import pandas as pd

df = pd.read_csv('raw_data.csv')

df.head()

    A  B  C grid_loc
0  19  3  5      0,A
1  19  3  5      0,A
2  19  3  5      0,A
3  19  4  5      0,A
4  19  4  5      0,A

In [ ]:
cols = df.select_dtypes(include=['number']).columns

df[cols] = df[cols].div(df[cols].sum(axis=1), axis=0)

df

             A         B         C grid_loc
0     0.703704  0.111111  0.185185      0,A
1     0.703704  0.111111  0.185185      0,A
2     0.703704  0.111111  0.185185      0,A
3     0.678571  0.142857  0.178571      0,A
4     0.678571  0.142857  0.178571      0,A
...        ...       ...       ...      ...
1181  0.072727  0.072727  0.854545      4,E
1182  0.071429  0.089286  0.839286      4,E
1183  0.071429  0.089286  0.839286      4,E
1184  0.071429  0.089286  0.839286      4,E
1185  0.070175  0.105263  0.824561      4,E

[1186 rows x 4 columns]

In [ ]:
from google.colab import files

df.to_csv('normalized_data.csv', index=False)
files.download('normalized_data.csv')